#!/usr/bin/awk -f
BEGIN {
    endianness = "big"
    placeholder = "-"
    OFS = " "
}
NR == 1 {
    n = NF
    k = 2 ^ n
}
NF == n {
    print "# " $0
    for (i = 1; i < k; ++i) {
        printf i ":"
        for (j = n; j > 0; --j) {
            if (rshift(i, j - 1) % 2) {
                if (endianness == "little") {
                    printf $j
                } else if (endianness == "big") {
                    printf $(n - j + 1)
                } else {
                    print "invalid endianness: " endianness > "/dev/stderr"
                    exit 1
                }
            } else {
                printf placeholder
            }
            if (j != 1)
                printf OFS
        }
        print ""
    }
    print ""
}
NF != n {
    printf "skipping line %d: wrong number of fields\n", NR > "/dev/stderr"
}
